<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.1
 * FormDin Version: 5.0.0
 * 
 * System aw created in: 2023-08-21 14:08:51
 */
class ContatoVO
{
    private $id_contato = null;
    private $nome = null;
    private $ddi = null;
    private $ddd = null;
    private $celular = null;
    private $st_whatsapp = null;
    private $avisado = null;
    private $dtinclusao = null;
    private $dtalteracao = null;
    private $dtexclusao = null;
    public function __construct( $id_contato=null, $nome=null, $ddi=null, $ddd=null, $celular=null, $st_whatsapp=null, $avisado=null, $dtinclusao=null, $dtalteracao=null, $dtexclusao=null ) {
        $this->setId_contato( $id_contato );
        $this->setNome( $nome );
        $this->setDdi( $ddi );
        $this->setDdd( $ddd );
        $this->setCelular( $celular );
        $this->setSt_whatsapp( $st_whatsapp );
        $this->setAvisado( $avisado );
        $this->setDtinclusao( $dtinclusao );
        $this->setDtalteracao( $dtalteracao );
        $this->setDtexclusao( $dtexclusao );
    }
    //--------------------------------------------------------------------------------
    public function setId_contato( $strNewValue = null )
    {
        $this->id_contato = $strNewValue;
    }
    public function getId_contato()
    {
        return $this->id_contato;
    }
    //--------------------------------------------------------------------------------
    public function setNome( $strNewValue = null )
    {
        $this->nome = $strNewValue;
    }
    public function getNome()
    {
        return $this->nome;
    }
    //--------------------------------------------------------------------------------
    public function setDdi( $strNewValue = null )
    {
        $this->ddi = $strNewValue;
    }
    public function getDdi()
    {
        return $this->ddi;
    }
    //--------------------------------------------------------------------------------
    public function setDdd( $strNewValue = null )
    {
        $this->ddd = $strNewValue;
    }
    public function getDdd()
    {
        return $this->ddd;
    }
    //--------------------------------------------------------------------------------
    public function setCelular( $strNewValue = null )
    {
        $this->celular = $strNewValue;
    }
    public function getCelular()
    {
        return $this->celular;
    }
    //--------------------------------------------------------------------------------
    public function setSt_whatsapp( $strNewValue = null )
    {
        $this->st_whatsapp = $strNewValue;
    }
    public function getSt_whatsapp()
    {
        return $this->st_whatsapp;
    }
    //--------------------------------------------------------------------------------
    public function setAvisado( $strNewValue = null )
    {
        $this->avisado = $strNewValue;
    }
    public function getAvisado()
    {
        return $this->avisado;
    }
    //--------------------------------------------------------------------------------
    public function setDtinclusao( $strNewValue = null )
    {
        $this->dtinclusao = $strNewValue;
    }
    public function getDtinclusao()
    {
        return $this->dtinclusao;
    }
    //--------------------------------------------------------------------------------
    public function setDtalteracao( $strNewValue = null )
    {
        $this->dtalteracao = $strNewValue;
    }
    public function getDtalteracao()
    {
        return $this->dtalteracao;
    }
    //--------------------------------------------------------------------------------
    public function setDtexclusao( $strNewValue = null )
    {
        $this->dtexclusao = $strNewValue;
    }
    public function getDtexclusao()
    {
        return $this->dtexclusao;
    }
    //--------------------------------------------------------------------------------
}
?>