<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.1
 * FormDin Version: 5.0.0
 * 
 * System aw created in: 2023-08-21 14:08:51
 */
class MensagemVO
{
    private $id_mensagem = null;
    private $mensagem = null;
    private $dtinclusao = null;
    private $dtalteracao = null;
    private $dtexclusao = null;
    public function __construct( $id_mensagem=null, $mensagem=null, $dtinclusao=null, $dtalteracao=null, $dtexclusao=null ) {
        $this->setId_mensagem( $id_mensagem );
        $this->setMensagem( $mensagem );
        $this->setDtinclusao( $dtinclusao );
        $this->setDtalteracao( $dtalteracao );
        $this->setDtexclusao( $dtexclusao );
    }
    //--------------------------------------------------------------------------------
    public function setId_mensagem( $strNewValue = null )
    {
        $this->id_mensagem = $strNewValue;
    }
    public function getId_mensagem()
    {
        return $this->id_mensagem;
    }
    //--------------------------------------------------------------------------------
    public function setMensagem( $strNewValue = null )
    {
        $this->mensagem = $strNewValue;
    }
    public function getMensagem()
    {
        return $this->mensagem;
    }
    //--------------------------------------------------------------------------------
    public function setDtinclusao( $strNewValue = null )
    {
        $this->dtinclusao = $strNewValue;
    }
    public function getDtinclusao()
    {
        return $this->dtinclusao;
    }
    //--------------------------------------------------------------------------------
    public function setDtalteracao( $strNewValue = null )
    {
        $this->dtalteracao = $strNewValue;
    }
    public function getDtalteracao()
    {
        return $this->dtalteracao;
    }
    //--------------------------------------------------------------------------------
    public function setDtexclusao( $strNewValue = null )
    {
        $this->dtexclusao = $strNewValue;
    }
    public function getDtexclusao()
    {
        return $this->dtexclusao;
    }
    //--------------------------------------------------------------------------------
}
?>