<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.1
 * FormDin Version: 5.0.0
 * 
 * System aw created in: 2023-08-21 14:08:51
 */

class ContatoFormList extends TPage
{

    private static $formId ='form_contatoFormList'; //Form ID
    private static $primaryKey ='id_contato';
    protected $form; //Registration form Adianti
    protected $frm;  //Registration component FormDin 5
    protected $filter_criteria;
    protected $adianti_target_container;
    protected $datagrid; //Listing
    protected $pageNavigation;
    public $datagrid_form;

    // trait com onReload, onSearch, onDelete, onClear, onEdit, show
    use Adianti\Base\AdiantiStandardFormTrait;
    // trait com onReload, onSearch, onDelete...
    use Adianti\Base\AdiantiStandardListTrait;

    public function __construct($param = null)
    {
        parent::__construct();
        $this->setDatabase('whats_df'); // define the database
        $this->setActiveRecord('contato'); // define the Active Record
        $this->setDefaultOrder('id_contato', 'asc'); // define the default order
        $this->setLimit(20);
        $this->filter_criteria = new TCriteria;
        if(!empty($param['target_container'])){
            $this->adianti_target_container = $param['target_container'];
        }

        $this->frm = new TFormDin($this,_t('List').' contato',null,null,self::$formId);
        $frm = $this->frm;
        $frm->enableCSRFProtection(); // Protection cross-site request forgery 
        $frm->addHiddenField( self::$primaryKey );   // coluna chave da tabela
        $frm->addTextField('NOME', 'Nome',50,true,50);
        $frm->addTextField('DDI', 'Ddi',50,true,50);
        $frm->addTextField('DDD', 'Ddd',50,true,50);
        $frm->addTextField('CELULAR', 'Celular',50,true,50);
        $frm->addTextField('ST_WHATSAPP', 'Status Whatsapp',50,false,50);
        $frm->addTextField('AVISADO', 'Avisado',50,false,50);

        // O Adianti permite a Internacionalização - A função _t('string') serve
        //para traduzir termos no sistema. Veja ApplicationTranslator escrevendo
        //primeiro em ingles e depois traduzindo
        $frm->setActionLink( _t('Search'), 'onSearch', null, 'fas:search', '#2168bd');
        $frm->setActionLink( _t('Clear'), 'onClear', null, 'fa:eraser', 'red');
        $frm->setAction( _t('Register'), ['ContatoForm','onReload'], null, 'fa:plus-square', 'green' );

        $this->form = $frm->show();
        $this->form->setData( TSession::getValue(__CLASS__.'_filter_data'));

        $mixUpdateFields = self::$primaryKey.'|'.self::$primaryKey
                        .',NOME|NOME'
                        .',DDI|DDI'
                        .',DDD|DDD'
                        .',CELULAR|CELULAR'
                        .',ST_WHATSAPP|ST_WHATSAPP'
                        .',AVISADO|AVISADO'
                        .',DTINCLUSAO|DTINCLUSAO'
                        .',DTALTERACAO|DTALTERACAO'
                        .',DTEXCLUSAO|DTEXCLUSAO'
                        ;
        $grid = new TFormDinGrid($this,'gd','Data Grid');
        $grid->setUpdateFields($mixUpdateFields);
        $grid->addColumn(self::$primaryKey,'id');
        $grid->addColumn('NOME','Nome');
        $grid->addColumn('DDI','Ddi');
        $grid->addColumn('DDD','Ddd');
        $grid->addColumn('CELULAR','Celular');
        $grid->addColumn('ST_WHATSAPP','Status Whatsapp');
        $grid->addColumn('AVISADO','Avisado');

        $this->datagrid = $grid->show();
        $this->pageNavigation = $grid->getPageNavigation();
        $panelGroupGrid = $grid->getPanelGroupGrid();


        // creates the page structure using a table
        $formDinBreadCrumb = new TFormDinBreadCrumb(__CLASS__);
        $vbox = $formDinBreadCrumb->getAdiantiObj();
        $vbox->add($this->form);
        $vbox->add($panelGroupGrid);

        // add the table inside the page
        parent::add($vbox);
    }

    //--------------------------------------------------------------------------------
    /**
     * Close right panel
     */
     /*
    public function onClose()
    {
        TScript::create("Template.closeRightPanel()");
    } //END onClose
     */

    //--------------------------------------------------------------------------------
    /**
     * Clear filters
     */
    public function onClear()
    {
        $this->clearFilters();
        $this->onReload();
    } //END onClear

    //--------------------------------------------------------------------------------
    /**
     * Usado no TFormDinGrid
     */
    public function setDatagrid_form($datagrid_form)
    {
        if( !is_object($datagrid_form) ){
            throw new InvalidArgumentException(TFormDinMessage::ERROR_FD5_OBJ_ADI);
        }
        $this->datagrid_form = $datagrid_form;
    }
    public function getDatagrid_form()
    {
        return $this->datagrid_form;
    }

}