<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.1
 * FormDin Version: 5.0.0
 * 
 * System aw created in: 2023-08-21 14:08:51
 */

class MensagemFormList extends TPage
{

    private static $formId ='form_mensagemFormList'; //Form ID
    private static $primaryKey ='ID_MENSAGEM';
    protected $form; //Registration form Adianti
    protected $frm;  //Registration component FormDin 5
    protected $filter_criteria;
    protected $adianti_target_container;
    protected $datagrid; //Listing
    protected $pageNavigation;
    public $datagrid_form;

    // trait com onReload, onSearch, onDelete, onClear, onEdit, show
    use Adianti\Base\AdiantiStandardFormTrait;
    // trait com onReload, onSearch, onDelete...
    use Adianti\Base\AdiantiStandardListTrait;

    public function __construct($param = null)
    {
        parent::__construct();
        $this->setDatabase('maindatabase'); // define the database
        $this->setActiveRecord('mensagem'); // define the Active Record
        $this->setDefaultOrder('ID_MENSAGEM', 'asc'); // define the default order
        $this->setLimit(20);
        $this->filter_criteria = new TCriteria;
        if(!empty($param['target_container'])){
            $this->adianti_target_container = $param['target_container'];
        }

        $this->frm = new TFormDin($this,_t('List').' mensagem',null,null,self::$formId);
        $frm = $this->frm;
        $frm->enableCSRFProtection(); // Protection cross-site request forgery 
        $frm->addHiddenField( self::$primaryKey );   // coluna chave da tabela
        $frm->addTextField('MENSAGEM', 'Mensagem',50,true,50);
        $frm->addDateField('DTINCLUSAO', 'Data Inclusão',true,null,null,null,null,'dd/mm/yyyy',null,null,null,null,'yyyy-mm-dd');
        $frm->addDateField('DTALTERACAO', 'Data Alteração',false,null,null,null,null,'dd/mm/yyyy',null,null,null,null,'yyyy-mm-dd');
        $frm->addDateField('DTEXCLUSAO', 'Data Exclusão',false,null,null,null,null,'dd/mm/yyyy',null,null,null,null,'yyyy-mm-dd');

        // O Adianti permite a Internacionalização - A função _t('string') serve
        //para traduzir termos no sistema. Veja ApplicationTranslator escrevendo
        //primeiro em ingles e depois traduzindo
        $frm->setActionLink( _t('Search'), 'onSearch', null, 'fas:search', '#2168bd');
        $frm->setActionLink( _t('Clear'), 'onClear', null, 'fa:eraser', 'red');
        $frm->setAction( _t('Register'), ['mensagemForm','onReload'], null, 'fa:plus-square', 'green' );

        $this->form = $frm->show();
        $this->form->setData( TSession::getValue(__CLASS__.'_filter_data'));

        $mixUpdateFields = self::$primaryKey.'|'.self::$primaryKey
                        .',MENSAGEM|MENSAGEM'
                        .',DTINCLUSAO|DTINCLUSAO'
                        .',DTALTERACAO|DTALTERACAO'
                        .',DTEXCLUSAO|DTEXCLUSAO'
                        ;
        $grid = new TFormDinGrid($this,'gd','Data Grid');
        $grid->setUpdateFields($mixUpdateFields);
        $grid->addColumn(self::$primaryKey,'id');
        $grid->addColumn('MENSAGEM','Mensagem');
        $grid->addColumnFormatDate('DTINCLUSAO','Data Inclusão',null,'left','dd/mm/yyyy');
        $grid->addColumnFormatDate('DTALTERACAO','Data Alteração',null,'left','dd/mm/yyyy');
        $grid->addColumnFormatDate('DTEXCLUSAO','Data Exclusão',null,'left','dd/mm/yyyy');

        $this->datagrid = $grid->show();
        $this->pageNavigation = $grid->getPageNavigation();
        $panelGroupGrid = $grid->getPanelGroupGrid();


        // creates the page structure using a table
        $formDinBreadCrumb = new TFormDinBreadCrumb(__CLASS__);
        $vbox = $formDinBreadCrumb->getAdiantiObj();
        $vbox->add($this->form);
        $vbox->add($panelGroupGrid);

        // add the table inside the page
        parent::add($vbox);
    }

    //--------------------------------------------------------------------------------
    /**
     * Close right panel
     */
     /*
    public function onClose()
    {
        TScript::create("Template.closeRightPanel()");
    } //END onClose
     */

    //--------------------------------------------------------------------------------
    /**
     * Clear filters
     */
    public function onClear()
    {
        $this->clearFilters();
        $this->onReload();
    } //END onClear

    //--------------------------------------------------------------------------------
    /**
     * Usado no TFormDinGrid
     */
    public function setDatagrid_form($datagrid_form)
    {
        if( !is_object($datagrid_form) ){
            throw new InvalidArgumentException(TFormDinMessage::ERROR_FD5_OBJ_ADI);
        }
        $this->datagrid_form = $datagrid_form;
    }
    public function getDatagrid_form()
    {
        return $this->datagrid_form;
    }

}